module.exports = {
    sections: [
        {
            key: 'basic',
            title: '基本信息',
            fields: [
                { key: 'title', label: '报销名称', type: 'text', required: true },
                { key: 'applicantName', label: '报销人员', type: 'text', required: true },
                { key: 'departmentName', label: '所属部门', type: 'text', required: true },
                { key: 'reason', label: '事由说明', type: 'textarea', required: true },
                { key: 'reimbursementUnitName', label: '报销单位名称', type: 'text' },
            ],
        },
        {
            key: 'meeting',
            title: '会议费信息',
            fields: [
                { key: 'meetingName', label: '会议名称', type: 'text', required: true },
                { key: 'meetingDate', label: '会议时间', type: 'text' },
                { key: 'startDate', label: '会议开始日期', type: 'date' },
                { key: 'endDate', label: '会议结束日期', type: 'date' },
                { key: 'meetingLocation', label: '会议地点', type: 'text' },
                { key: 'meetingDays', label: '会议天数', type: 'number' },
                { key: 'attendeeCount', label: '参会人数', type: 'number' },
                { key: 'staffCount', label: '工作人员人数', type: 'number' },
                { key: 'meetingCategory', label: '会议类别', type: 'text' },
                { key: 'meetingPlanNo', label: '会议计划序号', type: 'text' },
                { key: 'approvalNo', label: '审批或批件名称', type: 'text' },
                { key: 'hasMeetingPlan', label: '是否纳入会议计划', type: 'boolean' },
                { key: 'hasMeetingApproval', label: '是否有审批材料', type: 'boolean' },
                { key: 'hasMeetingNotice', label: '是否有会议通知', type: 'boolean' },
                { key: 'hasAttendanceList', label: '是否有签到表/参会名单', type: 'boolean' },
                { key: 'hasSettlement', label: '是否有结算单', type: 'boolean' },
                { key: 'hasInvoice', label: '是否有发票', type: 'boolean' },
                { key: 'hasPaymentProof', label: '是否有付款凭证', type: 'boolean' },
                { key: 'accommodationAmount', label: '住宿费', type: 'money' },
                { key: 'mealAmount', label: '伙食费', type: 'money' },
                { key: 'venueRentAmount', label: '场地租金', type: 'money' },
                { key: 'materialAmount', label: '资料费', type: 'money' },
                { key: 'transportAmount', label: '交通费', type: 'money' },
                { key: 'otherAmount', label: '其他费用', type: 'money' },
                { key: 'invoiceAmount', label: '发票金额合计', type: 'money' },
                { key: 'applyAmount', label: '申请报销金额', type: 'money' },
                { key: 'paymentAmount', label: '支付金额', type: 'money' },
                { key: 'totalAmount', label: '金额合计', type: 'money' },
                { key: 'attachmentCount', label: '附件张数', type: 'number' },
                { key: 'remark', label: '备注', type: 'textarea' },
            ],
        },
    ],
};
