const { createOcrProfile } = require('../shared/ocrProfileFactory');
const ocrPrompt = require('./ocrPrompt');

module.exports = createOcrProfile({
    scenarioType: 'meeting',
    label: '会议费报销',
    ownerCity: '会议费开发地市',
    documentTypes: [
        'meetingNotice',
        'meetingApproval',
        'meetingPlan',
        'attendanceList',
        'meetingSettlement',
        'accommodationList',
        'normalInvoice',
        'paymentProof',
        'other',
    ],
    keywords: [
        '会议',
        '会务',
        '参会',
        '会议费',
        '会议通知',
        '会议审批',
        '会议请示',
        '会议计划',
        '全市性会议计划',
        '签到表',
        '参会名单',
        '会议结算',
        '费用明细',
        '住宿清单',
        '住宿明细',
        '场地租金',
        '会场费',
        '会议室',
        '付款凭证',
    ],
    promptFocus: '会议费场景 OCR：重点识别审批依据、业务时间、地点或对象、人数、金额、发票和清单明细。',
    outputNote: '本场景只服务 会议费 开发调试；其他事项场景仅作为展示和借鉴。',
    ...ocrPrompt,
});
